language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover ./tests/Coverage/Clover.xml

after_success:
  - php vendor/bin/php-coveralls
